<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="anymal_simple">

  <!-- Constants -->
  <xacro:property name="body_length" value="0.6"/>
  <xacro:property name="body_width" value="0.4"/>
  <xacro:property name="body_height" value="0.2"/>
  <xacro:property name="upper_leg_length" value="0.3"/>
  <xacro:property name="lower_leg_length" value="0.3"/>
  <xacro:property name="foot_radius" value="0.035"/>
  
  <!-- Physics properties -->
  <xacro:property name="body_mass" value="35.0"/>
  <xacro:property name="hip_mass" value="2.5"/>
  <xacro:property name="upper_leg_mass" value="2.0"/>
  <xacro:property name="lower_leg_mass" value="1.2"/>
  <xacro:property name="foot_mass" value="0.15"/>
  
  <!-- Friction and damping -->
  <xacro:property name="joint_damping" value="0.5"/>
  <xacro:property name="joint_friction" value="0.1"/>
  <xacro:property name="foot_friction_mu1" value="1.5"/>
  <xacro:property name="foot_friction_mu2" value="1.5"/>

  <!-- Materials -->
  <material name="body_color">
    <color rgba="0.8 0.8 0.8 1.0"/>
  </material>
  
  <material name="leg_color">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>

  <!-- Base link (body) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="body_color"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.8</mu>
            <mu2>0.8</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${body_mass}"/>
      <inertia 
        ixx="${body_mass * (body_width*body_width + body_height*body_height) / 12.0}" 
        ixy="0.0" 
        ixz="0.0" 
        iyy="${body_mass * (body_length*body_length + body_height*body_height) / 12.0}" 
        iyz="0.0" 
        izz="${body_mass * (body_length*body_length + body_width*body_width) / 12.0}"/>
    </inertial>
  </link>
  
  <!-- IMU link -->
  <link name="imu_link">
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>
  
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  
  <!-- IMU sensor plugin -->
  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <ros>
          <namespace>/</namespace>
          <remapping>~/out:=imu</remapping>
        </ros>
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Leg macro -->
  <xacro:macro name="leg" params="name x y reflect">
    
    <!-- Hip joint (HAA - Hip Abduction/Adduction) -->
    <joint name="${name}_haa_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${name}_hip_link"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="-0.4" upper="0.4" effort="80" velocity="12"/>
      <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
    </joint>

    <link name="${name}_hip_link">
      <visual>
        <origin xyz="0 ${reflect*0.03} 0" rpy="0 1.5708 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.08"/>
        </geometry>
        <material name="leg_color"/>
      </visual>
      <collision>
        <origin xyz="0 ${reflect*0.03} 0" rpy="0 1.5708 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.08"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 ${reflect*0.03} 0" rpy="0 0 0"/>
        <mass value="${hip_mass}"/>
        <inertia ixx="0.002" ixy="0.0" ixz="0.0" iyy="0.002" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <!-- Hip flexion joint (HFE - Hip Flexion/Extension) -->
    <joint name="${name}_hfe_joint" type="revolute">
      <parent link="${name}_hip_link"/>
      <child link="${name}_upper_leg_link"/>
      <origin xyz="0 ${reflect*0.06} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.8" upper="1.8" effort="80" velocity="12"/>
      <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
    </joint>

    <link name="${name}_upper_leg_link">
      <visual>
        <origin xyz="0 0 -${upper_leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.025" length="${upper_leg_length}"/>
        </geometry>
        <material name="leg_color"/>
      </visual>
      <collision>
        <origin xyz="0 0 -${upper_leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.025" length="${upper_leg_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 -${upper_leg_length/2}" rpy="0 0 0"/>
        <mass value="${upper_leg_mass}"/>
        <inertia 
          ixx="${upper_leg_mass * (3*0.025*0.025 + upper_leg_length*upper_leg_length) / 12.0}" 
          ixy="0.0" 
          ixz="0.0" 
          iyy="${upper_leg_mass * (3*0.025*0.025 + upper_leg_length*upper_leg_length) / 12.0}" 
          iyz="0.0" 
          izz="${upper_leg_mass * 0.025*0.025 / 2.0}"/>
      </inertial>
    </link>

    <!-- Knee joint (KFE - Knee Flexion/Extension) -->
    <joint name="${name}_kfe_joint" type="revolute">
      <parent link="${name}_upper_leg_link"/>
      <child link="${name}_lower_leg_link"/>
      <origin xyz="0 0 -${upper_leg_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-2.7" upper="0.6" effort="80" velocity="12"/>
      <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
    </joint>

    <link name="${name}_lower_leg_link">
      <visual>
        <origin xyz="0 0 -${lower_leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.02" length="${lower_leg_length}"/>
        </geometry>
        <material name="leg_color"/>
      </visual>
      <collision>
        <origin xyz="0 0 -${lower_leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.02" length="${lower_leg_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 -${lower_leg_length/2}" rpy="0 0 0"/>
        <mass value="${lower_leg_mass}"/>
        <inertia 
          ixx="${lower_leg_mass * (3*0.02*0.02 + lower_leg_length*lower_leg_length) / 12.0}" 
          ixy="0.0" 
          ixz="0.0" 
          iyy="${lower_leg_mass * (3*0.02*0.02 + lower_leg_length*lower_leg_length) / 12.0}" 
          iyz="0.0" 
          izz="${lower_leg_mass * 0.02*0.02 / 2.0}"/>
      </inertial>
    </link>

    <!-- Foot -->
    <link name="${name}_foot_link">
      <visual>
        <geometry>
          <sphere radius="${foot_radius}"/>
        </geometry>
        <material name="leg_color"/>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${foot_radius}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>${foot_friction_mu1}</mu>
              <mu2>${foot_friction_mu2}</mu2>
              <slip1>0.0</slip1>
              <slip2>0.0</slip2>
            </ode>
          </friction>
          <contact>
            <ode>
              <kp>1000000.0</kp>
              <kd>100.0</kd>
              <max_vel>0.01</max_vel>
              <min_depth>0.001</min_depth>
            </ode>
          </contact>
        </surface>
      </collision>
      <inertial>
        <mass value="${foot_mass}"/>
        <inertia 
          ixx="${2.0 * foot_mass * foot_radius * foot_radius / 5.0}" 
          ixy="0.0" 
          ixz="0.0" 
          iyy="${2.0 * foot_mass * foot_radius * foot_radius / 5.0}" 
          iyz="0.0" 
          izz="${2.0 * foot_mass * foot_radius * foot_radius / 5.0}"/>
      </inertial>
    </link>

    <joint name="${name}_foot_joint" type="fixed">
      <parent link="${name}_lower_leg_link"/>
      <child link="${name}_foot_link"/>
      <origin xyz="0 0 -${lower_leg_length}" rpy="0 0 0"/>
    </joint>
    
    <!-- Gazebo-specific properties for foot -->
    <gazebo reference="${name}_foot_link">
      <mu1>${foot_friction_mu1}</mu1>
      <mu2>${foot_friction_mu2}</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>0.01</maxVel>
      <material>Gazebo/FlatBlack</material>
    </gazebo>

  </xacro:macro>

  <!-- Create all four legs -->
  <xacro:leg name="lf" x="${body_length/2-0.05}" y="${body_width/2}" reflect="1"/>
  <xacro:leg name="rf" x="${body_length/2-0.05}" y="-${body_width/2}" reflect="-1"/>
  <xacro:leg name="lh" x="-${body_length/2+0.05}" y="${body_width/2}" reflect="1"/>
  <xacro:leg name="rh" x="-${body_length/2+0.05}" y="-${body_width/2}" reflect="-1"/>

  <!-- Camera sensor -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="body_color"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${body_length/2+0.02} 0 ${body_height/2 + 0.03}" rpy="0 0.2 0"/>
  </joint>

  <!-- Camera sensor plugin -->
  <gazebo reference="camera_link">
    <sensor type="camera" name="camera">
      <always_on>true</always_on>
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <ros>
          <namespace>/</namespace>
          <remapping>~/image_raw:=camera/image_raw</remapping>
          <remapping>~/camera_info:=camera/camera_info</remapping>
        </ros>
        <camera_name>camera</camera_name>
        <frame_name>camera_link</frame_name>
        <hack_baseline>0.07</hack_baseline>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Depth camera -->
  <link name="camera_depth_link">
    <visual>
      <geometry>
        <box size="0.03 0.09 0.03"/>
      </geometry>
      <material name="body_color"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.09 0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.08"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_depth_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_depth_link"/>
    <origin xyz="${body_length/2+0.02} 0 ${body_height/2 + 0.05}" rpy="0 0.2 0"/>
  </joint>

  <!-- Depth camera sensor plugin -->
  <gazebo reference="camera_depth_link">
    <sensor type="depth" name="depth_camera">
      <always_on>true</always_on>
      <update_rate>20.0</update_rate>
      <camera name="depth">
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>10.0</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </camera>
      <plugin name="depth_camera_controller" filename="libgazebo_ros_camera.so">
        <ros>
          <namespace>/</namespace>
          <remapping>~/image_raw:=camera/depth/image_raw</remapping>
          <remapping>~/camera_info:=camera/depth/camera_info</remapping>
          <remapping>~/depth/image_raw:=camera/depth/image_raw</remapping>
          <remapping>~/points:=camera/depth/points</remapping>
        </ros>
        <camera_name>depth_camera</camera_name>
        <frame_name>camera_depth_optical_frame</frame_name>
        <hack_baseline>0.07</hack_baseline>
        <min_depth>0.1</min_depth>
        <max_depth>10.0</max_depth>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Additional optical frame -->
  <link name="camera_depth_optical_frame"/>
  <joint name="camera_depth_optical_joint" type="fixed">
    <parent link="camera_depth_link"/>
    <child link="camera_depth_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>
  
  <!-- Gazebo materials -->
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
    <mu1>0.8</mu1>
    <mu2>0.8</mu2>
  </gazebo>

  <!-- Gazebo ros2_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find terrain_description)/config/anymal_controllers.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- ros2_control configuration -->
  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    
    <!-- Left Front leg joints -->
    <joint name="lf_haa_joint">
      <command_interface name="position">
        <param name="min">-0.4</param>
        <param name="max">0.4</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="lf_hfe_joint">
      <command_interface name="position">
        <param name="min">-1.8</param>
        <param name="max">1.8</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="lf_kfe_joint">
      <command_interface name="position">
        <param name="min">-2.7</param>
        <param name="max">0.6</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    
    <!-- Right Front leg joints -->
    <joint name="rf_haa_joint">
      <command_interface name="position">
        <param name="min">-0.4</param>
        <param name="max">0.4</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="rf_hfe_joint">
      <command_interface name="position">
        <param name="min">-1.8</param>
        <param name="max">1.8</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="rf_kfe_joint">
      <command_interface name="position">
        <param name="min">-2.7</param>
        <param name="max">0.6</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    
    <!-- Left Hind leg joints -->
    <joint name="lh_haa_joint">
      <command_interface name="position">
        <param name="min">-0.4</param>
        <param name="max">0.4</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="lh_hfe_joint">
      <command_interface name="position">
        <param name="min">-1.8</param>
        <param name="max">1.8</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="lh_kfe_joint">
      <command_interface name="position">
        <param name="min">-2.7</param>
        <param name="max">0.6</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    
    <!-- Right Hind leg joints -->
    <joint name="rh_haa_joint">
      <command_interface name="position">
        <param name="min">-0.4</param>
        <param name="max">0.4</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="rh_hfe_joint">
      <command_interface name="position">
        <param name="min">-1.8</param>
        <param name="max">1.8</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="rh_kfe_joint">
      <command_interface name="position">
        <param name="min">-2.7</param>
        <param name="max">0.6</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
  </ros2_control>

</robot>